### ISSUE TITLE
Upgrade to logback 1.1.7 breaks this library when additionalFields are used - tests missing?

### ISSUE THREAD

**Issue by wujek-srujek** [pukkaone/logback-gelf#13]
When the 'additionalFiels' element is used in XML configuration, logback 1.1.7 results in the following configuration error:

```
java.lang.IllegalStateException: Logback configuration error detected: 
ERROR in ch.qos.logback.core.joran.action.NestedBasicPropertyIA - Unexpected aggregationType AS_BASIC_PROPERTY_COLLECTION
```

The ERROR line is repeated as many times as there are additionalFields.

Basically, logback 1.1.7 is broken: http://jira.qos.ch/browse/LOGBACK-1158, http://jira.qos.ch/browse/LOGBACK-1164 and possible more, all fixed here: https://github.com/qos-ch/logback/commit/2ba396a20e44d2f. The fix will be available in 1.1.8, not yet released.

I guess there is nothing to be done as the only difference between logback-gelf 1.1.8 and 1.1.9 is the upgrade to logback 1.1.7, and people can just force the earlier lib. But, there seems to be a test missing which tries a full configuration with logback, which would catch such a logback regression.

**Comment by pukkaone** [comment]
I agree there should be a test, but that test belongs in logback. It should not be this project's responsibility to test another project's implementation.
