### ISSUE TITLE
Provide the custom facility to log messages

### ISSUE THREAD

**Issue by mundrusatish** [pukkaone/logback-gelf#5]
Thank you for providing the utility to transfer the logs into GrayLog2 server.

Is it possible to sent facility like USER, kern, deamon, mail and etc as referred in below link.
http://en.wikipedia.org/wiki/Syslog

Because when I sent messages, it shows the graylog specific facility.

Thanks,
Satish

**Comment by mundrusatish** [comment]
And also provide any documentation for setup and configuring the tcp over ssl configuration.
Example configuration would be helpful.

Specifically provide example of the usage of the property "sslTrustAllCertificates"
Thanks

**Comment by pukkaone** [comment]
To configure TCP over SSL, add the prefix `ssl:` to the vaue of the `graylogHost` option. Set `sslTrustAllCertificates` if you don't want to check the server certificate was signed by a certificate authority (CA) in the Java trusted CA certificate store. These options are documented in the README.adoc file.
