### ISSUE TITLE
GelfAMQPSender channel confirmation issue

### ISSUE THREAD

**Issue by IgorPerikov** [pukkaone/logback-gelf#9]
Hi. 
Using AMQPSender produce IllegalStateException here: 
https://github.com/pukkaone/logback-gelf/blob/master/src/main/java/com/github/pukkaone/gelf/protocol/GelfAMQPSender.java#L76
and as a result sends (maxRetries+1) messages. As mentioned in rabbitmq javadoc it happens when calling waitForConfirms() on non-confirm channel: https://www.rabbitmq.com/releases/rabbitmq-java-client/current-javadoc/com/rabbitmq/client/Channel.html#waitForConfirms(). Calling confirmSelect() on channel before waitForConfirms() solves the problem. Contact me if I need to make any changes for merging this fix to fit your repo.

**Comment by pukkaone** [comment]
https://github.com/t0xa/gelfj/issues/72 fixes this same issue.
